name: EngraveMMO
version: 1.0
main: com.RoyalNinja.Main
description: EngraveMMO Core plugin.
depend: [EngraveMMOAPI]
commands:
     cutscene:
         usage: /<command>
         description: Cutscene creator.